### PR TITLE
Add template for captions field

### PR DESCRIPTION
**Pull request by froboy**
Adds twig to change the `Caption` title to `h3`. To be merged with https://github.com/MidCamp/hatter-v2/pull/8

### CODE REVIEW

**Comment by andrewolson** [comment]
Will this update to the theme also update the 2019 and 2018 theme versions of the site?

**Comment by froboy** [comment]
@andrewolson yes. This theme applies to all the sites that are live.

**Comment by andrewolson** [comment]
@froboy It just struck me that this should be labeled "Transcript" instead of "Captions".

Is it possible to update the PR? I don't want to hold this up, but that is ultimately what this field is housing now. Captions are for YouTube, but this is truly a Transcript.

**Comment by froboy** [comment]
Closing this in favor of #353 which is demo-able.

**Pull request closed without merging**
