### PR TITLE
Feature venue content type

### PR DESCRIPTION
**Pull request by josephdpurcell**

### CODE REVIEW

**Comment by josephdpurcell** [comment]
TODO:

1. Add an address field (need to validate bcmath is available on panthon, see [tweet](https://twitter.com/josephdpurcell/status/769659045833768962))
1. Once the event taxonomy is in, update the event field to point to that taxonomy
1. Write a test

Anyone is welcome to take this over :)

**Comment by zendoodles** [comment]
Nope. You're not allowed to bail on this one @josephdpurcell. Looks like bcmath is available on Pantheon. :)

**Comment by josephdpurcell** [comment]
Is this the combo that works?

* https://www.drupal.org/project/geofield
* https://www.drupal.org/project/addressfield

**Comment by josephdpurcell** [comment]
“drupal/address": “1.x-dev", "drupal/geocoder": "2.0.0-alpha4", "drupal/geocoder_geofield": “^2.0@alpha”, "drupal/geolocation": “^1.8”.

Address is the field and widget for the form. Geocoder_geofield codes the info from the address field into the geolocation field.

**Comment by labbydev** [comment]
@josephdpurcell it doesn't look like this includes the event taxonomy or linking up the field to that taxonomy

**Comment by josephdpurcell** [comment]
The event things will be done in #17 OR in a follow up PR related to Trello tickets "Topic" or "Event".

**Pull request merged**
