### PR TITLE
Homepage styleguide updates

### PR DESCRIPTION
**Pull request by aCyborg**
Creates Map component

Still need to add in a marker and reposition the map itself.

### CODE REVIEW

**Comment by aCyborg** [comment]
Actually apparently this has everything in it....I thought everything else was merged already but it seems I was wrong

**Comment by aCyborg** [comment]
This is the geojson for the location. I'm having trouble integrating it.

var geojson = [
  {
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [41.924137, -87.655084]
    }
  }
];

**Comment by labbydev** [comment]
@aCyborg I merged master into develop. Now everything is appearing correctly there.

**Comment by aCyborg** [comment]
Someone can you review this, or also help poke the map location if you'd like.

**Pull request merged**
