### PR TITLE
Sessions view and Trainings view

### PR DESCRIPTION
**Pull request by zendoodles**
`sessions` and `training` need to be added to the `Topic Types` vocabulary, and this may need some tweaks as a result of that content.

### Sessions
* Navigate to `/node/add/topic`
* Create a Topic with the type `session`
* Save as "Submitted"
* Navigate to `/submitted-sessions`
* Observe you see the teaser for the session you created
* Update the moderation status to "Accepted"
* Navigate to `/accepted-sessions`
* Observe you see the teaser for the session you created

### Trainings
* Navigate to `/node/add/topic`
* Create a Topic with the type `training`
* Save as "Submitted"
* Navigate to `/submitted-trainings`
* Observe you see the teaser for the session you created
* Update the moderation status to "Accepted"
* Navigate to `/accepted-trainings`
* Observe you see the teaser for the session you created

## What's missing
* No dates on Topics. What do these need?
* No session tracks. What should the tracks be?

### CODE REVIEW

**Comment by froboy** [comment]
Todo:
- [ ] node/add/topic goes to a 404. this should have a login and redirect.
- [x] messages don't display

**Comment by froboy** [comment]
I've added Sessions and Trainings to the prod site in the order that this expects so we won't have to update it.

**Comment by froboy** [comment]
OK, sessions works great, but the view for trainings doesn't exist.

**Comment by froboy** [comment]
Ok, I've updated with the training list, but if this is to fulfill the requirements for #53 then it still needs some theming work...
- how should we list things (table? grid?)
- need to remove submission info
- prob need more info on topics? see https://2017.midcamp.org/node/add/session

**Comment by labbydev** [comment]
* [ ] Session Title
* [ ] Session Track (filtering is a nice to have)
* [ ] Neither table nor node should display the user submitted information
* [ ] Add session length options 30min, 45min
* [ ] Add training length for half day and full day

**Pull request merged**
