### PR TITLE
Bunch o fixes

### PR DESCRIPTION
**Pull request by froboy**
- Allow rendering referencing users without elevated permissions
- Restore underlines on links
- Fix bulk operations

### CODE REVIEW

**Comment by tekNorah** [comment]
@froboy checks failed!

**Comment by tekNorah** [comment]
QA Failed for:

- Speakers are not displaying on the Accep
Screenshot_20240204_193732_Brave - Nightly
Screenshot_20240204_193005_Brave - Nightly
ted Session view for Anonymous users
- Delete multiple nodes using bulk operations

**Comment by tekNorah** [comment]
Need QA Steps for the underline links issue

**Comment by tekNorah** [comment]
Ahh... @froboy looks like the build failed:
Screenshot_20240204_194536_Brave - Nightly

**Comment by froboy** [comment]
@tekNorah the build fails, but that wasn't the problem here (that's a task for another issue)

I've merged https://github.com/MidCamp/midcamp/pull/494 and it's deploying now. Should be ready for testing in a few minutes.

**Pull request merged**
